wordpress:
  image: wordpress
  links:
    - db:mysql
  ports:
    - 8080:80
  volumes:
    - .:/var/www/html/wp-content/themes/wpmvc:ro

db:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
